#include "pmi/manifest.hpp"
#include <regex>
#include <sstream>
namespace pmi {
static std::string meta(const GgufFile& f,const std::string& k){auto i=f.metadata.find(k);return i==f.metadata.end()?"":i->second.text;}
ModelManifest build_manifest(const GgufFile& f){ModelManifest m; m.model_architecture=meta(f,"general.architecture");m.quantization=meta(f,"general.file_type");m.file_size=f.file_size;m.tensor_data_offset=f.tensor_data_offset;std::regex layer_re(".*\\.layers\\.([0-9]+)\\..*|blk\\.([0-9]+)\\..*");std::regex expert_re(".*(?:experts|expert)[._]([0-9]+)(?:[._].*)?");for(const auto& t:f.tensors){ManifestTensor base;base.name=t.name;base.source_tensor_name=t.name;base.shape=t.shape;base.ggml_type=t.ggml_type;base.offset=t.offset;base.byte_length=t.byte_length;base.absolute_offset=t.absolute_offset;base.required_alignment=32;std::smatch s;if(std::regex_match(base.name,s,layer_re)){auto idx=s[1].matched?1:2;base.layer=std::stoi(s[idx]);}if(std::regex_match(base.name,s,expert_re))base.expert_id=std::stoi(s[1]);auto n=base.name;for(auto& c:n)c=static_cast<char>(std::tolower(c));if(n.find("vision")!=std::string::npos||n.find("mtp")!=std::string::npos)base.semantic_class=TensorClass::OPTIONAL;else if(n.find("shexp")!=std::string::npos||n.find("shared_expert")!=std::string::npos)base.semantic_class=TensorClass::ALWAYS_ACTIVE;else if(base.expert_id>=0||n.find("experts")!=std::string::npos||n.find("_exps")!=std::string::npos||n.find("expert_")!=std::string::npos)base.semantic_class=TensorClass::ROUTED_EXPERT;else if(n.find("ngram")!=std::string::npos||n.find("ple_")!=std::string::npos||n.find("per_layer_token_embd")!=std::string::npos||n.find("sparse_embedding")!=std::string::npos)base.semantic_class=TensorClass::SPARSE_LOOKUP;else if(base.layer>=0||n.find("router")!=std::string::npos||n.find("norm")!=std::string::npos||n.find("token_embd")!=std::string::npos||n.find("output")!=std::string::npos)base.semantic_class=TensorClass::ALWAYS_ACTIVE;
 if(base.semantic_class==TensorClass::ROUTED_EXPERT&&base.expert_id<0&&n.find("exps")!=std::string::npos&&base.shape.size()>=2){uint64_t count=base.shape.back();auto expected=meta(f,m.model_architecture+".expert_count");if(!expected.empty()&&std::stoull(expected)!=count)throw std::runtime_error("expert tensor dimension disagrees with model expert_count");auto slice_shape=base.shape;slice_shape.pop_back();uint64_t slice_bytes=ggml_tensor_nbytes(base.ggml_type,slice_shape);if(slice_bytes*count!=base.byte_length)throw std::runtime_error("packed expert tensor size mismatch");for(uint64_t e=0;e<count;e++){auto x=base;x.expert_id=static_cast<int>(e);x.source_tensor_name=t.name;x.name=t.name+"#expert:"+std::to_string(e);x.shape=slice_shape;x.offset=t.offset+slice_bytes*e;x.absolute_offset=t.absolute_offset+slice_bytes*e;x.byte_length=slice_bytes;x.required_alignment=1;m.tensors.push_back(std::move(x));}}else m.tensors.push_back(std::move(base));}return m;}
std::string class_name(TensorClass c){switch(c){case TensorClass::ALWAYS_ACTIVE:return"ALWAYS_ACTIVE";case TensorClass::ROUTED_EXPERT:return"ROUTED_EXPERT";case TensorClass::SPARSE_LOOKUP:return"SPARSE_LOOKUP";case TensorClass::OPTIONAL:return"OPTIONAL";default:return"UNKNOWN";}}
static std::string esc(const std::string&s){std::string o;for(unsigned char c:s){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\b':o+="\\b";break;case '\f':o+="\\f";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;case '\t':o+="\\t";break;default:if(c<0x20){const char* h="0123456789abcdef";o+="\\u00";o+=h[c>>4];o+=h[c&15];}else o+=static_cast<char>(c);}}return o;}
std::string manifest_json(const ModelManifest&m){std::ostringstream o;o<<"{\"model_architecture\":\""<<esc(m.model_architecture)<<"\",\"quantization\":\""<<esc(m.quantization)<<"\",\"file_size\":"<<m.file_size<<",\"tensor_data_offset\":"<<m.tensor_data_offset<<",\"tensors\":[";for(size_t i=0;i<m.tensors.size();i++){const auto&t=m.tensors[i];if(i)o<<',';o<<"{\"name\":\""<<esc(t.name)<<"\",\"source_tensor\":\""<<esc(t.source_tensor_name)<<"\",\"dtype\":\""<<ggml_type_name(t.ggml_type)<<"\",\"offset\":"<<t.absolute_offset<<",\"byte_length\":"<<t.byte_length<<",\"class\":\""<<class_name(t.semantic_class)<<"\",\"layer\":"<<t.layer<<",\"expert_id\":"<<t.expert_id<<"}";}o<<"]}";return o.str();}
}
